GET http://localhost:8000/users HTTP/1.1

##############################
POST http://localhost:8000/users/registration HTTP/1.1
Content-Type: application/json

{
  "username": "admin3",
  "password": "admin",
  "email": "admin@gmail.com",
  "birthdate": "2006-01-13"
}

###################################################
POST http://localhost:8000/users/login HTTP/1.1
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

##################################################

DELETE http://localhost:8000/users/1 HTTP/1.1

#################################################